/**
 * 💰 FINANCIAL & REGULATORY OPERATIONS
 * Banking operations + Auto-generated regulatory reports
 */

import { motion } from 'motion/react';
import { 
  DollarSign, TrendingUp, TrendingDown, Download, FileText,
  Calendar, CheckCircle2, AlertCircle, Building2, Globe,
  ArrowUpRight, ArrowDownRight, CreditCard, Briefcase,
  Shield, Users, Factory, BarChart3, Clock, Award, Eye
} from 'lucide-react';
import { toast } from 'sonner';
import { useState } from 'react';
import { format, addDays, startOfMonth, endOfMonth } from 'date-fns';

/**
 * ============================================================================
 * FINANCIAL OPERATIONS - Main Component Export
 * Combines banking operations and regulatory reporting
 * ============================================================================
 */

export function FinancialOperations() {
  return (
    <div className="space-y-6">
      <BankingOperationsHub />
      <AutoGeneratedRegulatoryReports />
    </div>
  );
}

/**
 * ============================================================================
 * 4. BANKING OPERATIONS HUB ⭐⭐⭐⭐⭐
 * Daily banking operations - not just bank selection
 * ============================================================================
 */

export function BankingOperationsHub() {
  const [selectedMonth, setSelectedMonth] = useState(format(new Date(), 'yyyy-MM'));

  const accounts = [
    {
      bank: 'Standard Chartered Bangladesh',
      type: 'Foreign Currency (USD)',
      balance: 487500,
      currency: 'USD',
      lastTransaction: '2026-02-04 10:35 AM'
    },
    {
      bank: 'HSBC Bangladesh',
      type: 'Local Currency (BDT)',
      balance: 12450000,
      currency: 'BDT',
      lastTransaction: '2026-02-04 02:15 PM'
    },
    {
      bank: 'Standard Chartered Bangladesh',
      type: 'LC Account',
      balance: 125000,
      currency: 'USD',
      lastTransaction: '2026-02-03 04:20 PM'
    }
  ];

  const transactions = [
    {
      date: '2026-02-04',
      type: 'Inward Remittance',
      description: 'Machinery import payment from parent company',
      amount: 125000,
      currency: 'USD',
      direction: 'in',
      status: 'completed',
      bbApproval: 'BB-IR-2026-0042'
    },
    {
      date: '2026-02-03',
      type: 'Outward Remittance',
      description: 'Dividend repatriation to shareholders',
      amount: 75000,
      currency: 'USD',
      direction: 'out',
      status: 'pending_bb_approval',
      bbApproval: 'Pending'
    },
    {
      date: '2026-02-02',
      type: 'LC Opening',
      description: 'Raw material purchase - Cotton from India',
      amount: 50000,
      currency: 'USD',
      direction: 'out',
      status: 'completed',
      bbApproval: 'BB-LC-2026-0215'
    },
    {
      date: '2026-02-01',
      type: 'Local Transfer',
      description: 'Salary payment to employees',
      amount: 1875000,
      currency: 'BDT',
      direction: 'out',
      status: 'completed',
      bbApproval: 'N/A'
    }
  ];

  const lcStatus = [
    {
      id: 'LC-2026-001',
      supplier: 'Machinery Corp (China)',
      amount: 450000,
      opened: '2026-01-15',
      expiry: '2026-03-15',
      status: 'documents_received',
      shipmentStatus: 'In transit',
      daysToExpiry: 39
    },
    {
      id: 'LC-2026-002',
      supplier: 'Raw Materials Ltd (India)',
      amount: 125000,
      opened: '2026-02-02',
      expiry: '2026-04-02',
      status: 'awaiting_shipment',
      shipmentStatus: 'Not shipped',
      daysToExpiry: 57
    }
  ];

  const loanFacility = {
    type: 'Working Capital Loan',
    sanctioned: 5000000, // BDT
    utilized: 3250000,
    available: 1750000,
    interestRate: 9.5,
    emiAmount: 145833,
    nextEmiDate: '2026-02-10',
    outstanding: 3250000
  };

  return (
    <div className="space-y-6">
      <div className="glass-card p-8 bg-gradient-to-r from-green-50 to-emerald-50 border-2 border-green-300">
        <h2 className="text-3xl font-bold mb-2 flex items-center gap-3">
          <DollarSign className="w-8 h-8 text-green-600" />
          Banking Operations Hub
        </h2>
        <p className="text-gray-600 mb-6">Daily banking operations & cash flow management</p>

        {/* Account Balances */}
        <div className="grid md:grid-cols-3 gap-6 mb-6">
          {accounts.map((account, idx) => (
            <div key={idx} className="p-6 bg-white rounded-xl border-2 border-gray-200">
              <p className="text-sm text-gray-600 mb-1">{account.bank}</p>
              <p className="text-xs text-gray-500 mb-3">{account.type}</p>
              <p className="text-3xl font-bold text-green-600 mb-2">
                {account.currency === 'USD' ? '$' : '৳'}
                {account.balance.toLocaleString()}
              </p>
              <p className="text-xs text-gray-500">
                Last transaction: {account.lastTransaction}
              </p>
            </div>
          ))}
        </div>

        {/* Recent Transactions */}
        <div className="glass-card p-6 bg-white mb-6">
          <h3 className="text-lg font-bold mb-4">Recent Transactions</h3>
          
          <div className="space-y-3">
            {transactions.map((txn, idx) => (
              <div key={idx} className="p-4 bg-gray-50 rounded-lg border border-gray-200">
                <div className="flex items-start justify-between mb-2">
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-1">
                      <h4 className="font-semibold text-gray-900">{txn.type}</h4>
                      <span className={`px-2 py-1 rounded-full text-xs font-semibold ${
                        txn.status === 'completed' ? 'bg-green-100 text-green-700' :
                        txn.status === 'pending_bb_approval' ? 'bg-orange-100 text-orange-700' :
                        'bg-blue-100 text-blue-700'
                      }`}>
                        {txn.status === 'completed' ? '✓ Completed' :
                         txn.status === 'pending_bb_approval' ? '⏳ Pending BB Approval' : 'Processing'}
                      </span>
                    </div>
                    <p className="text-sm text-gray-600 mb-1">{txn.description}</p>
                    <p className="text-xs text-gray-500">
                      BB Approval: {txn.bbApproval}
                    </p>
                  </div>
                  <div className="text-right ml-4">
                    <div className={`flex items-center gap-1 ${
                      txn.direction === 'in' ? 'text-green-600' : 'text-red-600'
                    }`}>
                      {txn.direction === 'in' ? <ArrowDownRight className="w-4 h-4" /> : <ArrowUpRight className="w-4 h-4" />}
                      <span className="text-lg font-bold">
                        {txn.currency === 'USD' ? '$' : '৳'}{txn.amount.toLocaleString()}
                      </span>
                    </div>
                    <p className="text-xs text-gray-500">{txn.date}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>

          <button
            onClick={() => toast.info('Opening full transaction history...')}
            className="w-full mt-4 px-4 py-2 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700"
          >
            View All Transactions
          </button>
        </div>

        {/* LC Tracking */}
        <div className="glass-card p-6 bg-white mb-6">
          <h3 className="text-lg font-bold mb-4">Letter of Credit (LC) Status</h3>

          <div className="space-y-4">
            {lcStatus.map((lc, idx) => (
              <div key={idx} className="p-4 bg-gradient-to-r from-blue-50 to-indigo-50 rounded-lg border-2 border-blue-200">
                <div className="flex items-start justify-between mb-3">
                  <div>
                    <h4 className="font-bold text-gray-900 mb-1">{lc.id}</h4>
                    <p className="text-sm text-gray-600">{lc.supplier}</p>
                  </div>
                  <div className="text-right">
                    <p className="text-xl font-bold text-blue-600">${lc.amount.toLocaleString()}</p>
                    <p className="text-xs text-gray-500">{lc.daysToExpiry} days to expiry</p>
                  </div>
                </div>

                <div className="grid md:grid-cols-3 gap-3 mb-3">
                  <div className="p-2 bg-white rounded border border-blue-200">
                    <p className="text-xs text-gray-600">Opened</p>
                    <p className="text-sm font-semibold">{lc.opened}</p>
                  </div>
                  <div className="p-2 bg-white rounded border border-blue-200">
                    <p className="text-xs text-gray-600">Expiry</p>
                    <p className="text-sm font-semibold">{lc.expiry}</p>
                  </div>
                  <div className="p-2 bg-white rounded border border-blue-200">
                    <p className="text-xs text-gray-600">Shipment</p>
                    <p className="text-sm font-semibold">{lc.shipmentStatus}</p>
                  </div>
                </div>

                <div className="flex items-center justify-between">
                  <span className={`px-3 py-1 rounded-full text-xs font-semibold ${
                    lc.status === 'documents_received' ? 'bg-green-100 text-green-700' :
                    lc.status === 'awaiting_shipment' ? 'bg-orange-100 text-orange-700' :
                    'bg-blue-100 text-blue-700'
                  }`}>
                    {lc.status === 'documents_received' ? '✓ Documents Received' :
                     lc.status === 'awaiting_shipment' ? '⏳ Awaiting Shipment' : 'Processing'}
                  </span>
                  <button
                    onClick={() => toast.info(`Viewing details for ${lc.id}...`)}
                    className="text-sm text-blue-600 hover:underline font-semibold"
                  >
                    View Details →
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Loan Facility */}
        <div className="glass-card p-6 bg-white">
          <h3 className="text-lg font-bold mb-4">Loan Facility Status</h3>

          <div className="grid md:grid-cols-2 gap-6 mb-4">
            <div>
              <div className="grid grid-cols-2 gap-4 mb-4">
                <div className="p-4 bg-blue-50 rounded-lg border border-blue-200">
                  <p className="text-sm text-gray-600 mb-1">Sanctioned</p>
                  <p className="text-2xl font-bold text-blue-600">৳{(loanFacility.sanctioned / 100000).toFixed(1)}L</p>
                </div>
                <div className="p-4 bg-green-50 rounded-lg border border-green-200">
                  <p className="text-sm text-gray-600 mb-1">Available</p>
                  <p className="text-2xl font-bold text-green-600">৳{(loanFacility.available / 100000).toFixed(1)}L</p>
                </div>
              </div>

              <div className="mb-4">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-sm text-gray-600">Utilization</span>
                  <span className="text-sm font-bold text-orange-600">
                    {((loanFacility.utilized / loanFacility.sanctioned) * 100).toFixed(1)}%
                  </span>
                </div>
                <div className="h-3 bg-gray-200 rounded-full overflow-hidden">
                  <div 
                    className="h-full bg-orange-600"
                    style={{ width: `${(loanFacility.utilized / loanFacility.sanctioned) * 100}%` }}
                  />
                </div>
              </div>
            </div>

            <div className="space-y-3">
              <div className="p-4 bg-purple-50 rounded-lg border border-purple-200">
                <p className="text-sm text-gray-600 mb-1">Interest Rate</p>
                <p className="text-2xl font-bold text-purple-600">{loanFacility.interestRate}%</p>
              </div>
              <div className="p-4 bg-orange-50 rounded-lg border border-orange-200">
                <p className="text-sm text-gray-600 mb-1">Monthly EMI</p>
                <p className="text-2xl font-bold text-orange-600">৳{loanFacility.emiAmount.toLocaleString()}</p>
                <p className="text-xs text-gray-500 mt-1">Next EMI: {loanFacility.nextEmiDate}</p>
              </div>
            </div>
          </div>

          <div className="p-4 bg-blue-100 rounded-lg border border-blue-300">
            <p className="text-sm text-blue-800">
              ℹ️ <strong>Note:</strong> All loan transactions require Bangladesh Bank approval for amounts exceeding $10,000
            </p>
          </div>
        </div>

        {/* Monthly Banking Report */}
        <div className="mt-6 p-6 bg-gradient-to-r from-purple-50 to-blue-50 rounded-xl border-2 border-purple-300">
          <h3 className="text-lg font-bold text-purple-900 mb-3">📊 Monthly Banking Report to Bangladesh Bank</h3>
          <p className="text-sm text-purple-800 mb-4">
            Required monthly submission - auto-generated from your transactions
          </p>
          <div className="flex gap-3">
            <button
              onClick={() => toast.success('Generating monthly banking report...')}
              className="px-6 py-3 bg-purple-600 text-white rounded-lg font-semibold hover:bg-purple-700 flex items-center gap-2"
            >
              <Download className="w-5 h-5" />
              Download Report (PDF)
            </button>
            <button
              onClick={() => toast.info('Submitting report to Bangladesh Bank...')}
              className="px-6 py-3 bg-green-600 text-white rounded-lg font-semibold hover:bg-green-700"
            >
              Submit to Bangladesh Bank
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

/**
 * ============================================================================
 * 5. AUTO-GENERATED REGULATORY REPORTS ⭐⭐⭐⭐⭐
 * Government reports that would take hours - auto-generated in seconds
 * ============================================================================
 */

export function AutoGeneratedRegulatoryReports() {
  const [selectedReport, setSelectedReport] = useState('labor');

  const reports = [
    {
      id: 'labor',
      name: 'Monthly Labor Report',
      agency: 'DIFE (Dept of Inspection for Factories)',
      frequency: 'Monthly',
      nextDue: '2026-03-05',
      status: 'ready',
      autoFilled: 95
    },
    {
      id: 'export',
      name: 'Quarterly Export Report',
      agency: 'EPB (Export Promotion Bureau)',
      frequency: 'Quarterly',
      nextDue: '2026-04-15',
      status: 'in_progress',
      autoFilled: 78
    },
    {
      id: 'environment',
      name: 'Annual Environment Report',
      agency: 'DoE (Department of Environment)',
      frequency: 'Annually',
      nextDue: '2026-06-30',
      status: 'not_started',
      autoFilled: 45
    },
    {
      id: 'fire',
      name: 'Annual Fire Safety Report',
      agency: 'Fire Service & Civil Defence',
      frequency: 'Annually',
      nextDue: '2026-05-15',
      status: 'not_started',
      autoFilled: 60
    },
    {
      id: 'bida',
      name: 'BIDA Annual Survey',
      agency: 'Bangladesh Investment Development Authority',
      frequency: 'Annually',
      nextDue: '2026-12-31',
      status: 'not_started',
      autoFilled: 85
    },
    {
      id: 'investment',
      name: 'Investment Utilization Report',
      agency: 'BIDA',
      frequency: 'Annually',
      nextDue: '2026-12-31',
      status: 'ready',
      autoFilled: 100
    },
    {
      id: 'employment',
      name: 'Employment Generation Report',
      agency: 'Ministry of Labour',
      frequency: 'Quarterly',
      nextDue: '2026-04-15',
      status: 'ready',
      autoFilled: 100
    }
  ];

  const laborReportData = {
    totalWorkers: 350,
    male: 180,
    female: 170,
    skilled: 245,
    unskilled: 105,
    newHires: 15,
    resignations: 8,
    accidents: 2,
    trainingHours: 1400,
    avgWage: 18750,
    overtimeHours: 450
  };

  return (
    <div className="space-y-6">
      <div className="glass-card p-8 bg-gradient-to-r from-blue-50 to-purple-50 border-2 border-blue-300">
        <h2 className="text-3xl font-bold mb-2 flex items-center gap-3">
          <FileText className="w-8 h-8 text-blue-600" />
          Auto-Generated Regulatory Reports
        </h2>
        <p className="text-gray-600 mb-6">Required government reports - auto-generated from your operational data</p>

        {/* Reports Grid */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4 mb-6">
          {reports.map((report) => (
            <button
              key={report.id}
              onClick={() => setSelectedReport(report.id)}
              className={`p-6 rounded-xl border-2 text-left transition-all ${
                selectedReport === report.id
                  ? 'border-blue-600 bg-blue-50 shadow-lg'
                  : 'border-gray-300 hover:border-gray-400 bg-white'
              }`}
            >
              <div className="flex items-start justify-between mb-3">
                <h3 className="font-bold text-gray-900 text-sm">{report.name}</h3>
                <span className={`px-2 py-1 rounded-full text-xs font-semibold ${
                  report.status === 'ready' ? 'bg-green-100 text-green-700' :
                  report.status === 'in_progress' ? 'bg-blue-100 text-blue-700' :
                  'bg-gray-100 text-gray-700'
                }`}>
                  {report.status === 'ready' ? '✓ Ready' :
                   report.status === 'in_progress' ? '⏳ In Progress' : '📋 Not Started'}
                </span>
              </div>

              <p className="text-xs text-gray-600 mb-2">{report.agency}</p>
              <p className="text-xs text-gray-500 mb-3">{report.frequency} | Due: {report.nextDue}</p>

              <div className="mb-2">
                <div className="flex items-center justify-between mb-1">
                  <span className="text-xs text-gray-600">Auto-filled:</span>
                  <span className="text-xs font-bold text-blue-600">{report.autoFilled}%</span>
                </div>
                <div className="h-2 bg-gray-200 rounded-full overflow-hidden">
                  <div 
                    className="h-full bg-blue-600"
                    style={{ width: `${report.autoFilled}%` }}
                  />
                </div>
              </div>
            </button>
          ))}
        </div>

        {/* Selected Report Details */}
        {selectedReport === 'labor' && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="glass-card p-6 bg-white"
          >
            <h3 className="text-xl font-bold mb-4">Monthly Labor Report to DIFE</h3>
            <p className="text-sm text-gray-600 mb-6">
              Auto-populated from your HR system • Ready to submit
            </p>

            <div className="grid md:grid-cols-4 gap-4 mb-6">
              <div className="p-4 bg-blue-50 rounded-lg border border-blue-200">
                <p className="text-sm text-gray-600 mb-1">Total Workers</p>
                <p className="text-3xl font-bold text-blue-600">{laborReportData.totalWorkers}</p>
              </div>
              <div className="p-4 bg-purple-50 rounded-lg border border-purple-200">
                <p className="text-sm text-gray-600 mb-1">New Hires</p>
                <p className="text-3xl font-bold text-purple-600">{laborReportData.newHires}</p>
              </div>
              <div className="p-4 bg-orange-50 rounded-lg border border-orange-200">
                <p className="text-sm text-gray-600 mb-1">Safety Incidents</p>
                <p className="text-3xl font-bold text-orange-600">{laborReportData.accidents}</p>
              </div>
              <div className="p-4 bg-green-50 rounded-lg border border-green-200">
                <p className="text-sm text-gray-600 mb-1">Training Hours</p>
                <p className="text-3xl font-bold text-green-600">{laborReportData.trainingHours}</p>
              </div>
            </div>

            <div className="p-6 bg-gradient-to-r from-green-50 to-emerald-50 rounded-lg border-2 border-green-300 mb-6">
              <h4 className="font-bold text-green-900 mb-3">✅ Report Status: Ready to Submit</h4>
              <p className="text-sm text-green-800 mb-4">
                All required data fields have been automatically populated from your operational systems.
                Review and submit to DIFE.
              </p>
              <div className="flex gap-3">
                <button
                  onClick={() => toast.info('Opening report preview...')}
                  className="px-6 py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 flex items-center gap-2"
                >
                  <Eye className="w-5 h-5" />
                  Preview Report
                </button>
                <button
                  onClick={() => toast.success('Downloading report PDF...')}
                  className="px-6 py-3 bg-green-600 text-white rounded-lg font-semibold hover:bg-green-700 flex items-center gap-2"
                >
                  <Download className="w-5 h-5" />
                  Download PDF
                </button>
                <button
                  onClick={() => toast.success('Submitting to DIFE...')}
                  className="px-6 py-3 bg-purple-600 text-white rounded-lg font-semibold hover:bg-purple-700"
                >
                  Submit to DIFE
                </button>
              </div>
            </div>

            <div className="p-4 bg-blue-100 rounded-lg border border-blue-300">
              <p className="text-sm text-blue-800">
                ℹ️ <strong>Compliance Note:</strong> Monthly labor reports must be submitted by the 5th of each month as per Factory Act 2006
              </p>
            </div>
          </motion.div>
        )}

        {/* Report Calendar */}
        <div className="mt-6 glass-card p-6 bg-white">
          <h3 className="text-lg font-bold mb-4">Regulatory Reporting Calendar</h3>
          
          <div className="space-y-3">
            {reports
              .sort((a, b) => new Date(a.nextDue).getTime() - new Date(b.nextDue).getTime())
              .map((report, idx) => (
                <div key={idx} className="flex items-center justify-between p-4 bg-gray-50 rounded-lg border border-gray-200">
                  <div className="flex-1">
                    <h4 className="font-semibold text-gray-900">{report.name}</h4>
                    <p className="text-sm text-gray-600">{report.agency}</p>
                  </div>
                  <div className="text-right">
                    <p className="text-sm font-bold text-blue-600">{report.nextDue}</p>
                    <p className="text-xs text-gray-500">
                      {Math.ceil((new Date(report.nextDue).getTime() - new Date().getTime()) / (1000 * 60 * 60 * 24))} days remaining
                    </p>
                  </div>
                </div>
              ))}
          </div>

          <button
            onClick={() => toast.info('Exporting calendar to iCal format...')}
            className="w-full mt-4 px-4 py-2 bg-purple-600 text-white rounded-lg font-semibold hover:bg-purple-700"
          >
            Export to Calendar (iCal)
          </button>
        </div>
      </div>
    </div>
  );
}