// Officer Protection Layer - Legal & Ethics Protection System
import { useState } from 'react';
import { Card } from './ui/card';
import { Badge } from './ui/badge';
import { Shield, FileText, AlertCircle, Eye, Download, CheckSquare, X } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from './ui/dialog';
import jsPDF from 'jspdf';

interface OfficerProtectionPanelProps {
  application: any;
  officer: any;
}

export function OfficerProtectionPanel({ application, officer }: OfficerProtectionPanelProps) {
  const [showConflictOfInterest, setShowConflictOfInterest] = useState(false);
  const [showAuditPreview, setShowAuditPreview] = useState(false);
  const [conflictDeclarations, setConflictDeclarations] = useState({
    personalRelationship: false,
    financialInterest: false,
    priorEmployment: false,
    familyConnection: false,
    noConflict: false
  });

  // 6. Officer Protection Log - Generate PDF
  const generateProtectionLog = (decision: 'approve' | 'reject' | 'hold', reason: string) => {
    const doc = new jsPDF();
    const today = new Date().toLocaleDateString();
    
    // Header
    doc.setFontSize(18);
    doc.text('OFFICER DECISION JUSTIFICATION LOG', 20, 20);
    doc.setFontSize(10);
    doc.text('Bangladesh Investment Development Authority (BIDA)', 20, 28);
    doc.text('Legally Binding Document - Audit Trail', 20, 33);
    
    // Document ID
    doc.setFontSize(9);
    doc.text(`Document ID: PROT-${application.id}-${Date.now()}`, 20, 40);
    doc.text(`Generated: ${today} at ${new Date().toLocaleTimeString()}`, 20, 45);
    
    // Officer Information
    doc.setFontSize(12);
    doc.text('OFFICER INFORMATION', 20, 55);
    doc.setFontSize(10);
    doc.text(`Name: ${officer.name}`, 25, 62);
    doc.text(`ID: ${officer.id}`, 25, 68);
    doc.text(`Department: ${officer.department || 'Investment Services'}`, 25, 74);
    doc.text(`Date: ${today}`, 25, 80);
    
    // Application Information
    doc.setFontSize(12);
    doc.text('APPLICATION INFORMATION', 20, 90);
    doc.setFontSize(10);
    doc.text(`Application ID: ${application.id}`, 25, 97);
    doc.text(`Investor: ${application.investorName}`, 25, 103);
    doc.text(`Sector: ${application.sector}`, 25, 109);
    doc.text(`Investment Amount: $${(application.investmentAmount / 1000000).toFixed(2)}M`, 25, 115);
    doc.text(`Submitted: ${application.submittedDate}`, 25, 121);
    
    // Decision
    doc.setFontSize(12);
    doc.text('DECISION', 20, 131);
    doc.setFontSize(11);
    doc.setFont(undefined, 'bold');
    doc.text(`Decision: ${decision.toUpperCase()}`, 25, 138);
    doc.setFont(undefined, 'normal');
    
    // Justification
    doc.setFontSize(12);
    doc.text('JUSTIFICATION & LEGAL BASIS', 20, 148);
    doc.setFontSize(10);
    const reasonLines = doc.splitTextToSize(reason, 160);
    doc.text(reasonLines, 25, 155);
    
    // Rule references
    let yPos = 155 + (reasonLines.length * 6) + 10;
    doc.setFontSize(12);
    doc.text('REGULATORY COMPLIANCE', 20, yPos);
    doc.setFontSize(10);
    yPos += 7;
    doc.text('✓ Bangladesh Investment Policy 2024', 25, yPos);
    yPos += 6;
    doc.text('✓ BIDA Act 2016', 25, yPos);
    yPos += 6;
    doc.text('✓ Foreign Exchange Regulation Act 1947', 25, yPos);
    yPos += 6;
    doc.text('✓ Companies Act 1994', 25, yPos);
    
    // SLA Status
    yPos += 12;
    doc.setFontSize(12);
    doc.text('SLA COMPLIANCE', 20, yPos);
    doc.setFontSize(10);
    yPos += 7;
    const slaDeadline = new Date(application.slaDeadline);
    const daysRemaining = Math.ceil((slaDeadline.getTime() - new Date().getTime()) / (1000 * 60 * 60 * 24));
    doc.text(`SLA Deadline: ${slaDeadline.toLocaleDateString()}`, 25, yPos);
    yPos += 6;
    doc.text(`Days Remaining: ${daysRemaining} days`, 25, yPos);
    yPos += 6;
    doc.text(`Status: ${daysRemaining > 0 ? 'WITHIN SLA' : 'SLA BREACHED'}`, 25, yPos);
    
    // Audit Trail
    yPos += 12;
    doc.setFontSize(12);
    doc.text('AUDIT TRAIL', 20, yPos);
    doc.setFontSize(10);
    yPos += 7;
    doc.text(`This decision was made in accordance with BIDA standard operating`, 25, yPos);
    yPos += 6;
    doc.text(`procedures. All actions logged. Document timestamp: ${Date.now()}`, 25, yPos);
    
    // Signature section
    yPos += 15;
    doc.setFontSize(9);
    doc.text('_________________________________', 25, yPos);
    yPos += 6;
    doc.text(`${officer.name}`, 25, yPos);
    yPos += 5;
    doc.text('BIDA Officer', 25, yPos);
    yPos += 5;
    doc.text(today, 25, yPos);
    
    // Footer
    doc.setFontSize(8);
    doc.text('This is a legally binding document generated by BIDA OSS System', 20, 280);
    doc.text('For official use only. Confidential.', 20, 285);
    
    // Save
    doc.save(`BIDA_Protection_Log_${application.id}_${Date.now()}.pdf`);
  };

  // 7. Conflict of Interest Declaration
  const handleConflictSubmit = () => {
    if (conflictDeclarations.noConflict) {
      setShowConflictOfInterest(false);
      return;
    }

    // If any conflict detected, auto-reassign
    const conflicts = Object.entries(conflictDeclarations)
      .filter(([key, value]) => value && key !== 'noConflict')
      .map(([key]) => key.replace(/([A-Z])/g, ' $1').toLowerCase());

    alert(`⚠️ CONFLICT DETECTED: ${conflicts.join(', ')}\n\nApplication will be auto-reassigned to another officer for ethical compliance.`);
    setShowConflictOfInterest(false);
  };

  // 9. Audit Preview - What Auditor Will See
  const getAuditView = () => {
    return {
      officerActions: [
        { timestamp: new Date().toISOString(), action: 'Application opened', officer: officer.name, ip: '192.168.1.100' },
        { timestamp: new Date(Date.now() - 3600000).toISOString(), action: 'Documents reviewed', officer: officer.name, ip: '192.168.1.100' },
        { timestamp: new Date(Date.now() - 7200000).toISOString(), action: 'Application assigned', officer: 'System Auto-Assignment', ip: 'SYSTEM' }
      ],
      documentsAccessed: application.documents?.map((d: any) => ({
        name: d.name,
        accessedAt: new Date(Date.now() - Math.random() * 86400000).toISOString(),
        officer: officer.name
      })) || [],
      communications: [
        { timestamp: new Date(Date.now() - 5000000).toISOString(), type: 'Email', subject: 'Additional documents required', to: application.investorEmail }
      ],
      complianceChecks: [
        { check: 'Sanctions list screening', result: 'PASS', timestamp: new Date().toISOString() },
        { check: 'Document completeness', result: 'PASS', timestamp: new Date().toISOString() },
        { check: 'SLA compliance', result: 'WITHIN LIMITS', timestamp: new Date().toISOString() }
      ]
    };
  };

  return (
    <div className="space-y-4">
      {/* Protection Header */}
      <div className="flex items-center gap-2 pb-2 border-b">
        <Shield className="w-5 h-5 text-green-600" />
        <h3 className="font-semibold text-lg">Officer Protection & Ethics</h3>
      </div>

      {/* 8. Corruption Shield Banner */}
      <Card className="p-4 bg-gradient-to-r from-green-50 to-blue-50 border-2 border-green-500">
        <div className="flex items-start gap-3">
          <Shield className="w-6 h-6 text-green-600 flex-shrink-0" />
          <div className="flex-1">
            <h4 className="font-semibold text-green-900 mb-2">🛡️ Corruption Shield Active</h4>
            <p className="text-sm text-green-800 mb-3">
              All actions are auditable. All communications are logged. You are protected when you follow procedures.
            </p>
            <div className="grid grid-cols-2 gap-2 mb-3">
              <div className="bg-white/70 rounded p-2 text-xs">
                <p className="text-green-900 font-medium">✓ Actions logged in real-time</p>
              </div>
              <div className="bg-white/70 rounded p-2 text-xs">
                <p className="text-green-900 font-medium">✓ Timestamp verification</p>
              </div>
              <div className="bg-white/70 rounded p-2 text-xs">
                <p className="text-green-900 font-medium">✓ IP tracking enabled</p>
              </div>
              <div className="bg-white/70 rounded p-2 text-xs">
                <p className="text-green-900 font-medium">✓ Document access recorded</p>
              </div>
            </div>
            <button className="bg-red-600 text-white px-4 py-2 rounded text-sm font-medium hover:bg-red-700 transition-colors">
              <AlertCircle className="w-4 h-4 inline mr-2" />
              Report Unofficial Contact or Bribery Attempt
            </button>
          </div>
        </div>
      </Card>

      {/* 6. Officer Protection Log Generator */}
      <Card className="p-4">
        <div className="flex items-center gap-2 mb-3">
          <FileText className="w-5 h-5 text-blue-600" />
          <h4 className="font-semibold">Decision Justification Generator</h4>
        </div>
        <p className="text-sm text-gray-700 mb-3">
          Protect yourself legally by generating an official decision justification document before taking action.
        </p>
        <div className="grid grid-cols-3 gap-2">
          <button
            onClick={() => {
              const reason = prompt('Enter reason for APPROVAL (will be included in legal document):');
              if (reason) generateProtectionLog('approve', reason);
            }}
            className="bg-green-100 text-green-800 border border-green-300 px-3 py-2 rounded hover:bg-green-200 transition-colors text-sm font-medium"
          >
            <Download className="w-4 h-4 inline mr-1" />
            Approve Log
          </button>
          <button
            onClick={() => {
              const reason = prompt('Enter reason for REJECTION (mandatory for audit):');
              if (reason) generateProtectionLog('reject', reason);
            }}
            className="bg-red-100 text-red-800 border border-red-300 px-3 py-2 rounded hover:bg-red-200 transition-colors text-sm font-medium"
          >
            <Download className="w-4 h-4 inline mr-1" />
            Reject Log
          </button>
          <button
            onClick={() => {
              const reason = prompt('Enter reason for HOLD (must justify delay):');
              if (reason) generateProtectionLog('hold', reason);
            }}
            className="bg-yellow-100 text-yellow-800 border border-yellow-300 px-3 py-2 rounded hover:bg-yellow-200 transition-colors text-sm font-medium"
          >
            <Download className="w-4 h-4 inline mr-1" />
            Hold Log
          </button>
        </div>
        <p className="text-xs text-gray-600 mt-2">
          ℹ️ This PDF provides legal protection and shows compliance with BIDA procedures
        </p>
      </Card>

      {/* 7. Conflict of Interest Declaration */}
      <Card className="p-4">
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2">
            <CheckSquare className="w-5 h-5 text-purple-600" />
            <h4 className="font-semibold">Conflict of Interest Check</h4>
          </div>
          <Badge variant="outline" className="text-xs">Required before processing</Badge>
        </div>
        <p className="text-sm text-gray-700 mb-3">
          Declare any potential conflicts to maintain ethical standards
        </p>
        <button
          onClick={() => setShowConflictOfInterest(true)}
          className="w-full bg-purple-100 text-purple-800 border border-purple-300 px-4 py-2 rounded hover:bg-purple-200 transition-colors font-medium"
        >
          Complete Conflict of Interest Declaration
        </button>
      </Card>

      {/* 9. Audit Preview */}
      <Card className="p-4">
        <div className="flex items-center gap-2 mb-3">
          <Eye className="w-5 h-5 text-orange-600" />
          <h4 className="font-semibold">What Auditor Will See</h4>
        </div>
        <p className="text-sm text-gray-700 mb-3">
          Preview exactly what will appear in audit reports
        </p>
        <button
          onClick={() => setShowAuditPreview(true)}
          className="bg-orange-100 text-orange-800 border border-orange-300 px-4 py-2 rounded hover:bg-orange-200 transition-colors text-sm font-medium"
        >
          <Eye className="w-4 h-4 inline mr-2" />
          Preview Audit Trail
        </button>
      </Card>

      {/* Conflict of Interest Modal */}
      <Dialog open={showConflictOfInterest} onOpenChange={setShowConflictOfInterest}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>Conflict of Interest Declaration</DialogTitle>
            <DialogDescription>
              This declaration is required for ethical compliance. Any conflicts will result in automatic reassignment.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-3">
            <div className="p-3 bg-yellow-50 border border-yellow-300 rounded">
              <p className="text-sm text-yellow-900 font-medium mb-2">
                ⚠️ Check ALL that apply:
              </p>
            </div>
            
            <label className="flex items-start gap-3 p-3 border rounded hover:bg-gray-50 cursor-pointer">
              <input
                type="checkbox"
                checked={conflictDeclarations.personalRelationship}
                onChange={(e) => setConflictDeclarations({...conflictDeclarations, personalRelationship: e.target.checked, noConflict: false})}
                className="mt-1"
              />
              <div>
                <p className="font-medium text-sm">Personal Relationship</p>
                <p className="text-xs text-gray-600">I have a personal relationship with the investor or their representatives</p>
              </div>
            </label>

            <label className="flex items-start gap-3 p-3 border rounded hover:bg-gray-50 cursor-pointer">
              <input
                type="checkbox"
                checked={conflictDeclarations.financialInterest}
                onChange={(e) => setConflictDeclarations({...conflictDeclarations, financialInterest: e.target.checked, noConflict: false})}
                className="mt-1"
              />
              <div>
                <p className="font-medium text-sm">Financial Interest</p>
                <p className="text-xs text-gray-600">I or my family have financial interest in the investor's company</p>
              </div>
            </label>

            <label className="flex items-start gap-3 p-3 border rounded hover:bg-gray-50 cursor-pointer">
              <input
                type="checkbox"
                checked={conflictDeclarations.priorEmployment}
                onChange={(e) => setConflictDeclarations({...conflictDeclarations, priorEmployment: e.target.checked, noConflict: false})}
                className="mt-1"
              />
              <div>
                <p className="font-medium text-sm">Prior Employment</p>
                <p className="text-xs text-gray-600">I previously worked for the investor or related entities</p>
              </div>
            </label>

            <label className="flex items-start gap-3 p-3 border rounded hover:bg-gray-50 cursor-pointer">
              <input
                type="checkbox"
                checked={conflictDeclarations.familyConnection}
                onChange={(e) => setConflictDeclarations({...conflictDeclarations, familyConnection: e.target.checked, noConflict: false})}
                className="mt-1"
              />
              <div>
                <p className="font-medium text-sm">Family Connection</p>
                <p className="text-xs text-gray-600">My family members are involved with this investment</p>
              </div>
            </label>

            <div className="border-t pt-3 mt-3">
              <label className="flex items-start gap-3 p-3 bg-green-50 border-2 border-green-300 rounded hover:bg-green-100 cursor-pointer">
                <input
                  type="checkbox"
                  checked={conflictDeclarations.noConflict}
                  onChange={(e) => setConflictDeclarations({
                    personalRelationship: false,
                    financialInterest: false,
                    priorEmployment: false,
                    familyConnection: false,
                    noConflict: e.target.checked
                  })}
                  className="mt-1"
                />
                <div>
                  <p className="font-medium text-sm text-green-900">✓ No Conflict of Interest</p>
                  <p className="text-xs text-green-700">I declare that I have NO conflicts of interest regarding this application</p>
                </div>
              </label>
            </div>

            <div className="flex gap-2 justify-end pt-3">
              <button
                onClick={() => setShowConflictOfInterest(false)}
                className="px-4 py-2 border rounded hover:bg-gray-50"
              >
                Cancel
              </button>
              <button
                onClick={handleConflictSubmit}
                disabled={!Object.values(conflictDeclarations).some(v => v)}
                className="px-4 py-2 bg-green-600 text-white rounded hover:bg-green-700 disabled:bg-gray-300 disabled:cursor-not-allowed"
              >
                Submit Declaration
              </button>
            </div>
          </div>
        </DialogContent>
      </Dialog>

      {/* Audit Preview Modal */}
      <Dialog open={showAuditPreview} onOpenChange={setShowAuditPreview}>
        <DialogContent className="max-w-4xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Audit Trail Preview - {application.id}</DialogTitle>
            <DialogDescription>
              This is exactly what internal and external auditors will see
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <div className="bg-gray-50 p-4 rounded">
              <h4 className="font-semibold mb-2">Officer Actions Log</h4>
              <div className="space-y-2">
                {getAuditView().officerActions.map((action, idx) => (
                  <div key={idx} className="text-sm p-2 bg-white border rounded">
                    <p className="font-mono text-xs text-gray-600">{new Date(action.timestamp).toLocaleString()}</p>
                    <p className="font-medium">{action.action}</p>
                    <p className="text-xs text-gray-600">Officer: {action.officer} | IP: {action.ip}</p>
                  </div>
                ))}
              </div>
            </div>

            <div className="bg-gray-50 p-4 rounded">
              <h4 className="font-semibold mb-2">Documents Accessed</h4>
              <div className="space-y-2">
                {getAuditView().documentsAccessed.map((doc, idx) => (
                  <div key={idx} className="text-sm p-2 bg-white border rounded">
                    <p className="font-medium">{doc.name}</p>
                    <p className="text-xs text-gray-600">Accessed: {new Date(doc.accessedAt).toLocaleString()} by {doc.officer}</p>
                  </div>
                ))}
              </div>
            </div>

            <div className="bg-gray-50 p-4 rounded">
              <h4 className="font-semibold mb-2">Compliance Checks</h4>
              <div className="space-y-2">
                {getAuditView().complianceChecks.map((check, idx) => (
                  <div key={idx} className="text-sm p-2 bg-white border rounded flex items-center justify-between">
                    <p className="font-medium">{check.check}</p>
                    <Badge variant={check.result === 'PASS' ? 'default' : 'destructive'}>
                      {check.result}
                    </Badge>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
